import pandas as pd

CSV = r"C:\Users\ISLEM AYARI\OneDrive - AFDB\Documents\RASME\RASME_Projects\Global dashbord\kobo_04052026.csv"

df = pd.read_csv(CSV, header=None, on_bad_lines='skip', engine='python')

print("=== c1 country distribution (top 20) ===")
print(df.iloc[:, 1].value_counts().head(20))
print()
print("=== c2 version ===")
print(df.iloc[:, 2].value_counts())
print()
print("=== c9 sector (top 20) ===")
print(df.iloc[:, 9].value_counts().head(20))
print()
print("=== c10 category ===")
print(df.iloc[:, 10].value_counts())
print()
print("=== c26 STATUS ===")
print(df.iloc[:, 26].value_counts(dropna=False))
print()
print("=== c30 progress level ===")
print(df.iloc[:, 30].value_counts(dropna=False))
print()
print("=== c33 funder ===")
print(df.iloc[:, 33].value_counts().head(10))
print()
print("=== c39 agency type ===")
print(df.iloc[:, 39].value_counts().head(10))
print()
print("=== c61 contact role ===")
print(df.iloc[:, 61].value_counts())
print()
print("=== c75 validation status ===")
print(df.iloc[:, 75].value_counts(dropna=False))
print()
print("=== c1 unique countries (sorted) ===")
print(sorted(df.iloc[:, 1].dropna().astype(str).unique().tolist()))
